name: Node Publish

on:
  release:
    types: [published]

jobs:
  build_and_test:
    uses: ./.github/workflows/build-test-reusable.yml

  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
